pre-commit:
  parallel: true
  commands:
    lint:
      run: npm run lint
    lint-md:
      run: npm run lint:md
    format-check:
      run: npm run format

pre-push:
  parallel: true
  commands:
    build:
      run: npm run build
